name: Deploy (Vercel for Dashboard + Railway [Manual for collector])

on:
  push:
    branches:
      - deploy

jobs:
  dashboard:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
    
      - uses: pnpm/action-setup@v4
        with:
          version: 11.9.0
    
      - uses: actions/setup-node@v4
        with:
          node-version: 24
    
      - run: pnpm install
    
      - run: pnpm --filter @analytics/dashboard build
    
      - run: npm i -g vercel
    
      - run: |
          cd apps/dashboard
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
